repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.5 # Match the version in pyproject.toml if possible
    hooks:
    # Run the linter.
    -   id: ruff
        args: [--fix]
    # Run the formatter.
    -   id: ruff-format
