# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11" # Specify a Python version compatible with dependencies
    rust: "latest"
  apt_packages:
    - build-essential  # コンパイル用ツール群

# Build documentation in the docs/ directory with Sphinx
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - method: pip # Use pip for Read the Docs build environment
      path: .
      extra_requirements:
        - dev # Install dependencies from [project.optional-dependencies].dev
