name: Build & Publish PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # 1) コードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Python をセットアップ
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      # 3) Rust ツールチェインをセットアップ
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      # 4) maturin をインストール
      - name: Install maturin
        run: python -m pip install --upgrade maturin

      # 5) ビルド＆Publish
      - name: Build & Publish to PyPI
        run: |
          maturin build --release
          maturin publish --skip-existing --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
