name: Build & Publish to TestPyPI

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install uv CLI
        run: pip install uv

      - name: Install maturin
        run: uv pip install maturin --system

      - name: Build wheel
        run: uv run maturin build --release

      - name: Publish to TestPyPI
        run: |
          maturin publish \
            --username __token__ \
            --password ${{ secrets.TEST_PYPI_API_TOKEN }} \
            --repository-url https://test.pypi.org/legacy/

